### ISSUE TITLE
LivingColors component for ESPHome

### ISSUE THREAD

**Issue by rrooggiieerr** [hiteule/esp-livingcolors#1]
Hi!

Not an issue with your code or anything, but you might be interested to know I released a component for ESPHome which directly talks from the ESP to the CC2500 and implements the LivingColors 1st generation protocol

https://github.com/rrooggiieerr/esphome-livingcolors1

Kind regards,

Rogier

**Comment by hiteule** [comment]
Hi,
Wow, it look super nice!
I'll definitely take a look at it. Good job and thanks for the info :)
